### ISSUE TITLE
RuntimeError: shape '[batch size, 29, 3]' is invalid for input of size 315

### ISSUE THREAD

**Issue by wangxin1999** [ATAboukhadra/THOR-Net#8]
Traceback (most recent call last):
  File "main_THOR.py", line 174, in <module>
    loss_dict = model(inputs, targets)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/THOR-Net/models/generalized_rcnn.py", line 99, in forward
    detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, original_images, targets)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/THOR-Net/models/roi_heads.py", line 388, in forward
    rcnn_loss_keypoint, rcnn_loss_keypoint3d, rcnn_loss_mesh3d, rcnn_loss_photometric = keypointrcnn_loss(
  File "/root/autodl-tmp/THOR-Net/models/rcnn_loss.py", line 207, in keypointrcnn_loss
    keypoint3d_targets = torch.cat(kps3d, dim=0).view(N, K, 3)
RuntimeError: shape '[5, 29, 3]' is invalid for input of size 315

**Comment by wangxin1999** [comment]
I downloaded the dataset as required and ran the code. However, I encountered this error while calculating the loss. Is this due to a problem with data processing?

**Comment by wangxin1999** [comment]
Actually, I want to use train_ Is there any way to train the model with h03d.sh or a more detailed tutorial? Looking forward to your reply.

**Comment by ATAboukhadra** [comment]
Hi, 

At first glance, I notice that you're trying to resize a tensor that has 21 keypoints i.e. hand only while using K=29 i.e. hand + object. I'm not sure exactly how the tensor includes the hand only while K has both because this functionality should be handled in my code with flags. Please check from your side based on this info while I check whether this is a bug in my code.

**Comment by wangxin1999** [comment]
Thank you, perhaps some details here may need to be confirmed by you. I have not modified the relevant code, but have directly run the existing script.

**Comment by ATAboukhadra** [comment]
Could you provide me with the script that you tried to run so that I can reproduce the error

**Comment by wangxin1999** [comment]
mkdir checkpoints/hand-object
chmod a+x ./scripts/train_ho3d.sh
./scripts/train_ho3d.sh . i just ran this command, I'm not sure why there was an error, could it be a problem with my dataset? Can I link the server to you for you to check?

**Comment by ATAboukhadra** [comment]
Does your dataset only have hand keypoints? If that's the case then please remove the --object flag from scripts/train_ho3d.sh
